package ai.revexa.progress.service;

import ai.revexa.identity.domain.UserAccount;
import ai.revexa.progress.dto.ProgressDtos;
import java.time.Instant;
import java.time.format.DateTimeFormatter;
import java.time.ZoneOffset;
import java.util.List;
import org.springframework.stereotype.Service;

/**
 * Renders an exportable learning report.
 *
 * <p>Markdown is the export format on purpose: it pastes into a CV, a study log, a GitHub gist or a
 * mentor's inbox without any conversion step.
 */
@Service
public class ReportService {

    private static final DateTimeFormatter DATE = DateTimeFormatter.ofPattern("d MMM yyyy").withZone(ZoneOffset.UTC);

    private final ProgressService progress;
    private final RecommendationService recommendations;

    public ReportService(ProgressService progress, RecommendationService recommendations) {
        this.progress = progress;
        this.recommendations = recommendations;
    }

    public ProgressDtos.LearningReport generate(UserAccount user) {
        ProgressDtos.ProgressSummary summary = progress.summary(user.getId());
        ProgressDtos.RecommendationBundle bundle = recommendations.build(summary);
        String markdown = markdown(user, summary, bundle);
        return new ProgressDtos.LearningReport(
                user.getDisplayName(), Instant.now(), summary, bundle.recommendations(), markdown);
    }

    private String markdown(
            UserAccount user, ProgressDtos.ProgressSummary summary, ProgressDtos.RecommendationBundle bundle) {
        StringBuilder md = new StringBuilder();
        ProgressDtos.Headline headline = summary.headline();

        md.append("# Revexa learning report\n\n")
                .append("**")
                .append(user.getDisplayName())
                .append("** · generated ")
                .append(DATE.format(Instant.now()))
                .append("\n\n");

        md.append("## At a glance\n\n")
                .append("| Metric | Value |\n| --- | --- |\n")
                .append("| Problems attempted | ").append(headline.problemsAttempted()).append(" |\n")
                .append("| Reviews run | ").append(headline.reviewsRun()).append(" |\n")
                .append("| Optimal solutions | ").append(headline.optimalSolutions())
                .append(" (").append(headline.optimalRate()).append("%) |\n")
                .append("| Average solution score | ").append(headline.averageScore()).append("/100 |\n")
                .append("| Change over time | ")
                .append(headline.scoreDelta() >= 0 ? "+" : "")
                .append(headline.scoreDelta())
                .append(" points |\n")
                .append("| Current streak | ").append(headline.currentStreakDays()).append(" days |\n")
                .append("| Independence score | ").append(summary.hintDependency().independenceScore()).append("/100 |\n\n");

        appendTopics(md, "## Strengths", summary.strongTopics(), "No topic has enough optimal solutions to call a strength yet.");
        appendTopics(md, "## Weak spots", summary.weakTopics(), "Nothing is consistently weak — keep the variety up.");

        if (!summary.recurringMistakes().isEmpty()) {
            md.append("## Recurring mistakes\n\n");
            for (ProgressDtos.MistakePattern mistake : summary.recurringMistakes()) {
                md.append("- **").append(mistake.title()).append("** (")
                        .append(mistake.occurrences()).append("×) — ")
                        .append(mistake.coaching()).append("\n");
            }
            md.append('\n');
        }

        md.append("## Hint dependency\n\n")
                .append("**").append(summary.hintDependency().verdict()).append("** — ")
                .append(summary.hintDependency().advice()).append("\n\n");

        md.append("## What to do next\n\n");
        if (bundle.recommendations().isEmpty()) {
            md.append("Keep going — nothing specific stands out.\n\n");
        } else {
            for (ProgressDtos.Recommendation recommendation : bundle.recommendations()) {
                md.append("### ").append(recommendation.title()).append("\n\n")
                        .append(recommendation.reason()).append("\n\n")
                        .append(recommendation.action()).append("\n\n");
                if (!recommendation.practiceProblems().isEmpty()) {
                    md.append("Practice: ").append(String.join(", ", recommendation.practiceProblems())).append("\n\n");
                }
            }
        }

        md.append("---\n\n_Generated by Revexa.Ai — understanding first, answers last._\n");
        return md.toString();
    }

    private void appendTopics(
            StringBuilder md, String heading, List<ProgressDtos.TopicMastery> topics, String emptyMessage) {
        md.append(heading).append("\n\n");
        if (topics.isEmpty()) {
            md.append(emptyMessage).append("\n\n");
            return;
        }
        for (ProgressDtos.TopicMastery topic : topics) {
            md.append("- **").append(topic.topic()).append("** — ")
                    .append(topic.mastery()).append("% optimal across ")
                    .append(topic.attempts()).append(" attempts. ")
                    .append(topic.advice()).append("\n");
        }
        md.append('\n');
    }
}
